### ISSUE TITLE
Generated binary arguments conflict with Criterion's arguments

### ISSUE THREAD

**Issue by K900** [remi-dupre/aoc#1]
The only way to run the benchmarks currently is to run it with `--bench` , because Criterion [happens to ignore it when parsing its own CLI arguments](https://docs.rs/criterion/0.3.3/src/criterion/lib.rs.html#1151). 

Using the short form `-b` or any other argument conflicts with Criterion's own argument handling that macros use.

I'm not sure what a good solution here would be, but maybe it's better to manually instantiate a `Criterion` instance with sane defaults? The very basic way to do that would be

```diff
diff --git a/src/lib.rs b/src/lib.rs
index c4a4138..630822f 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -171,7 +171,9 @@ macro_rules! main {
             use $crate::criterion::*;

             pub fn run_benchs() {
-                main();
+                let mut crit = Criterion::default();
+                $($day(&mut crit))+;
+                crit.final_summary();
             }

             $(
@@ -196,9 +198,6 @@ macro_rules! main {
                     group.finish();
                 }
             )+
-
-            criterion_group!(benches, $($day),+);
-            criterion_main!(benches);
         }
     };
 }
```

A better setup would probably involve at least enabling colored and HTML output. I'd be interested in looking into it more if you're interested in this approach and want a patch.

**Comment by K900** [comment]
The other option is to manually post-process the arguments vector (can we even do that?) and remove the `bench` argument before handing things off to Criterion, but that seems even hackier.

**Comment by remi-dupre** [comment]
Hi! Thanks for your issue.

I've also been playing around with it yesterday and it seems that the issue is quite weird but we could get a fair workaround:

I have a POC on a branch that I didn't achieve to finish yesterday because I was too tired :(
https://github.com/remi-dupre/aoc/compare/criterion

My approach is, as you suggested, to instantiate manually [Criterion](https://docs.rs/criterion/0.3.3/criterion/struct.Criterion.html), it can help with the integration : getting coloration and selecting a subset of benches (which is my primary intention), but doesn't really solve the arg conflict issue because some parameters of criterions don't seem to be configurable without running `configure_from_args` (such as coloration).

To solve the above problem a fair solution would probably to make a PR to Criterion in order to make it more configurable, by adding more configuration methods or just adding a method similar to `configure_from_args` but which can take a custom `Vec` of arguments as input.

**Comment by K900** [comment]
It seems like the way to do it is to basically copy what `configure_from_args` does, but expose it as some other methods.

https://github.com/bheisler/criterion.rs/issues/452 might be relevant too.

**Comment by ThomasdenH** [comment]
Since #19, `configure_from_args` is not actually used anymore, so I think this could be closed. It may be nice to be able to specify some options for Criterion again, but this will probably have to be implemented manually and I think that should be another issue.

**Comment by K900** [comment]
Agreed.
